### ISSUE TITLE
The macro is not working in office 2016

### ISSUE THREAD

**Issue by dmontoya3** [triplebeta/TrelloExcelConnector#7]
After running the process to authorize the file, the buttons stay greyed-out.

**Comment by triplebeta** [comment]
Sorry to hear, let me check it, will be sometime next week.

Op vr 20 jul. 2018 22:39 schreef dmontoya3 <notifications@github.com>:

**Comment by triplebeta** [comment]
I also work with Excel 2016 (as part of Office 365), just checked to see what could cause this. There should be no difference between the Office versions since it does not rely on any Office-version specific settings. The buttons will become enabled only if your settings are correct.

I tested it again with invalid and valid settings to see that it indeed works like that and it did in my case. Can you please check that you pasted the values in the right textboxes? It's easy to swap some ;)

It might be helpful to press ALT-F11 (which starts up the Visual Basic tooling) to check the error message that you will see in the box at the bottom ("Direct" window). If one of the values is incorrect, it will tell you there.

Hope it helps.

**Comment by dmontoya3** [comment]
Thanks for your reply. I'm getting this error 
ERROR - RestHelpers.ExecuteRequest: -2147012739

**Comment by dmontoya3** [comment]
Also, I've just tried the 9 possible combinations of entering the key, token and secret codes just in case there was an issue with the labels or something else. Still with the 9 combinations, the buttons stay greyed out.

I have the "enable all macros" option activated in the trust center

**Comment by danielvand** [comment]
Hi,
I seem to have the same problem. The URL is perfectly OK (copy+paste in browser and it works). 
it gives the following error "An error occurred in the secure channel support " code: -2147012739 when calling Http.Send.

**Comment by danielvand** [comment]
Think I've the solution, in Public Function PrepareHttpRequest in "RestHelpers"
change 
Set Http = CreateObject("MSXML2.ServerXMLHTTP.6.0") 
to
Set Http = CreateObject("MSXML2.XMLHTTP.6.0")

and comment out Http.setTimeouts TimeoutMS, TimeoutMS, TimeoutMS, TimeoutMS (so it won't have time outs, but that function isn't available)

It now works for me!

**Comment by dmontoya3** [comment]
That did the trick. Thanks for the help!!

**Comment by triplebeta** [comment]
@danielvand thanks for posting the solution! Seems like I could not reproduce it since I use no proxy server. I updated the macro according and published the update as version 1.2.2.
